using System;
using System.Text;
using AE2Unity;
using UnityEngine;

namespace AE2Unity.Editor
{
    internal static class Ae2ShaderCodeGenerator
    {
        public static string GeneratePreviewShader(Ae2ShaderClip clip, string shaderName, bool hasBakedFrames)
        {
            var document = clip != null ? clip.Document : null;
            var comp = document?.comp ?? new Ae2ShaderComp();
            var layers = document?.layers ?? Array.Empty<Ae2ShaderLayer>();
            var warnings = clip?.ImportWarnings ?? Array.Empty<string>();

            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by AE2Unity.");
            builder.AppendLine(hasBakedFrames
                ? "// This shader plays baked AE composition frames from generated atlases."
                : "// Metadata-only preview. Re-export with Bake animation enabled for full composition playback.");
            builder.AppendLine($"// Source comp: {EscapeComment(comp.name)} ({comp.width}x{comp.height}, {comp.frameRate:0.###} fps, {comp.duration:0.###}s)");
            builder.AppendLine("//");
            builder.AppendLine("// Exported layers:");
            for (var i = 0; i < layers.Length; i++)
            {
                var layer = layers[i];
                if (layer == null)
                {
                    continue;
                }

                builder.AppendLine($"// - {layer.index}: {EscapeComment(layer.name)} [{EscapeComment(layer.type)}], blend={EscapeComment(layer.blendMode)}, opacity={layer.transform?.opacity?.value ?? 100f:0.###}");
            }

            if (warnings.Length > 0)
            {
                builder.AppendLine("//");
                builder.AppendLine("// Import warnings:");
                for (var i = 0; i < warnings.Length; i++)
                {
                    builder.AppendLine($"// - {EscapeComment(warnings[i])}");
                }
            }

            builder.AppendLine($"Shader \"{EscapeShaderPath(shaderName)}\"");
            builder.AppendLine("{");
            builder.AppendLine("    Properties");
            builder.AppendLine("    {");
            builder.AppendLine("        _MainTex (\"Texture\", 2D) = \"white\" {}");
            builder.AppendLine("        [NoScaleOffset] _FrameAtlas0 (\"Baked Frames 0\", 2D) = \"black\" {}");
            builder.AppendLine("        [NoScaleOffset] _FrameAtlas1 (\"Baked Frames 1\", 2D) = \"black\" {}");
            builder.AppendLine("        [NoScaleOffset] _FrameAtlas2 (\"Baked Frames 2\", 2D) = \"black\" {}");
            builder.AppendLine("        [NoScaleOffset] _FrameAtlas3 (\"Baked Frames 3\", 2D) = \"black\" {}");
            builder.AppendLine("        _Tint (\"Tint\", Color) = (1, 1, 1, 1)");
            builder.AppendLine("        _Opacity (\"Opacity\", Range(0, 1)) = 1");
            builder.AppendLine("        _AeTime (\"AE Time\", Float) = 0");
            builder.AppendLine("        [Toggle] _AutoPlay (\"Auto Play\", Float) = 0");
            builder.AppendLine("        [Toggle] _Loop (\"Loop\", Float) = 1");
            builder.AppendLine("        _PlaybackSpeed (\"Playback Speed\", Float) = 1");
            builder.AppendLine("        [HideInInspector] _BakedFrameCount (\"Baked Frame Count\", Float) = 0");
            builder.AppendLine("        [HideInInspector] _FramesPerAtlas (\"Frames Per Atlas\", Float) = 1");
            builder.AppendLine("        [HideInInspector] _AtlasColumns (\"Atlas Columns\", Float) = 1");
            builder.AppendLine("        [HideInInspector] _AtlasRows (\"Atlas Rows\", Float) = 1");
            builder.AppendLine("        [HideInInspector] _FrameRate (\"Frame Rate\", Float) = 24");
            builder.AppendLine("        [HideInInspector] _Duration (\"Duration\", Float) = 1");
            builder.AppendLine($"        _CompSize (\"Comp Size\", Vector) = ({Mathf.Max(1, comp.width)}, {Mathf.Max(1, comp.height)}, {1f / Mathf.Max(1, comp.width):0.########}, {1f / Mathf.Max(1, comp.height):0.########})");
            builder.AppendLine("    }");
            builder.AppendLine("    SubShader");
            builder.AppendLine("    {");
            builder.AppendLine("        Tags { \"RenderPipeline\"=\"UniversalPipeline\" \"Queue\"=\"Transparent\" \"RenderType\"=\"Transparent\" \"IgnoreProjector\"=\"True\" }");
            builder.AppendLine("        Blend SrcAlpha OneMinusSrcAlpha");
            builder.AppendLine("        Cull Off");
            builder.AppendLine("        ZWrite Off");
            builder.AppendLine("        Pass");
            builder.AppendLine("        {");
            builder.AppendLine("            Name \"AE2UnityGeneratedPreview\"");
            builder.AppendLine("            HLSLPROGRAM");
            builder.AppendLine("            #pragma vertex Vert");
            builder.AppendLine("            #pragma fragment Frag");
            builder.AppendLine("            #pragma target 3.0");
            builder.AppendLine("            #include \"Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl\"");
            builder.AppendLine("            struct Attributes { float4 positionOS : POSITION; float2 uv : TEXCOORD0; half4 color : COLOR; };");
            builder.AppendLine("            struct Varyings { float4 positionHCS : SV_POSITION; float2 uv : TEXCOORD0; half4 color : COLOR; };");
            builder.AppendLine("            TEXTURE2D(_MainTex);");
            builder.AppendLine("            SAMPLER(sampler_MainTex);");
            builder.AppendLine("            TEXTURE2D(_FrameAtlas0);");
            builder.AppendLine("            SAMPLER(sampler_FrameAtlas0);");
            builder.AppendLine("            TEXTURE2D(_FrameAtlas1);");
            builder.AppendLine("            SAMPLER(sampler_FrameAtlas1);");
            builder.AppendLine("            TEXTURE2D(_FrameAtlas2);");
            builder.AppendLine("            SAMPLER(sampler_FrameAtlas2);");
            builder.AppendLine("            TEXTURE2D(_FrameAtlas3);");
            builder.AppendLine("            SAMPLER(sampler_FrameAtlas3);");
            builder.AppendLine("            CBUFFER_START(UnityPerMaterial)");
            builder.AppendLine("                float4 _MainTex_ST;");
            builder.AppendLine("                half4 _Tint;");
            builder.AppendLine("                half _Opacity;");
            builder.AppendLine("                float _AeTime;");
            builder.AppendLine("                float _AutoPlay;");
            builder.AppendLine("                float _Loop;");
            builder.AppendLine("                float _PlaybackSpeed;");
            builder.AppendLine("                float _BakedFrameCount;");
            builder.AppendLine("                float _FramesPerAtlas;");
            builder.AppendLine("                float _AtlasColumns;");
            builder.AppendLine("                float _AtlasRows;");
            builder.AppendLine("                float _FrameRate;");
            builder.AppendLine("                float _Duration;");
            builder.AppendLine("                float4 _CompSize;");
            builder.AppendLine("            CBUFFER_END");
            builder.AppendLine("            Varyings Vert(Attributes input)");
            builder.AppendLine("            {");
            builder.AppendLine("                Varyings output;");
            builder.AppendLine("                output.positionHCS = TransformObjectToHClip(input.positionOS.xyz);");
            builder.AppendLine("                output.uv = TRANSFORM_TEX(input.uv, _MainTex);");
            builder.AppendLine("                output.color = input.color;");
            builder.AppendLine("                return output;");
            builder.AppendLine("            }");
            builder.AppendLine("            half4 SampleBakedFrame(float2 uv)");
            builder.AppendLine("            {");
            builder.AppendLine("                float frameRate = max(1.0, _FrameRate);");
            builder.AppendLine("                float duration = max(1.0 / frameRate, _Duration);");
            builder.AppendLine("                float playbackTime = _AutoPlay > 0.5 ? _Time.y * _PlaybackSpeed : _AeTime;");
            builder.AppendLine("                playbackTime = max(0.0, playbackTime);");
            builder.AppendLine("                playbackTime = _Loop > 0.5 ? fmod(playbackTime, duration) : min(playbackTime, duration - 0.5 / frameRate);");
            builder.AppendLine("                float frameIndex = min(_BakedFrameCount - 1.0, floor(playbackTime * frameRate + 0.0001));");
            builder.AppendLine("                float framesPerAtlas = max(1.0, _FramesPerAtlas);");
            builder.AppendLine("                float atlasIndex = floor(frameIndex / framesPerAtlas);");
            builder.AppendLine("                float localIndex = frameIndex - atlasIndex * framesPerAtlas;");
            builder.AppendLine("                float columns = max(1.0, _AtlasColumns);");
            builder.AppendLine("                float rows = max(1.0, _AtlasRows);");
            builder.AppendLine("                float column = fmod(localIndex, columns);");
            builder.AppendLine("                float row = floor(localIndex / columns);");
            builder.AppendLine("                float2 atlasUv = (float2(column, row) + uv) / float2(columns, rows);");
            builder.AppendLine("                if (atlasIndex < 0.5) return SAMPLE_TEXTURE2D(_FrameAtlas0, sampler_FrameAtlas0, atlasUv);");
            builder.AppendLine("                if (atlasIndex < 1.5) return SAMPLE_TEXTURE2D(_FrameAtlas1, sampler_FrameAtlas1, atlasUv);");
            builder.AppendLine("                if (atlasIndex < 2.5) return SAMPLE_TEXTURE2D(_FrameAtlas2, sampler_FrameAtlas2, atlasUv);");
            builder.AppendLine("                return SAMPLE_TEXTURE2D(_FrameAtlas3, sampler_FrameAtlas3, atlasUv);");
            builder.AppendLine("            }");
            builder.AppendLine("            half4 Frag(Varyings input) : SV_Target");
            builder.AppendLine("            {");
            builder.AppendLine("                half4 color = _BakedFrameCount > 0.5");
            builder.AppendLine("                    ? SampleBakedFrame(input.uv)");
            builder.AppendLine("                    : SAMPLE_TEXTURE2D(_MainTex, sampler_MainTex, input.uv);");
            builder.AppendLine("                color *= _Tint * input.color;");
            builder.AppendLine("                color.a *= _Opacity;");
            builder.AppendLine("                return color;");
            builder.AppendLine("            }");
            builder.AppendLine("            ENDHLSL");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("    FallBack Off");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string EscapeShaderPath(string value)
        {
            return string.IsNullOrWhiteSpace(value)
                ? "AE2Unity/Generated"
                : value.Replace("\\", "/").Replace("\"", string.Empty);
        }

        private static string EscapeComment(string value)
        {
            return string.IsNullOrEmpty(value)
                ? string.Empty
                : value.Replace("\r", " ").Replace("\n", " ");
        }
    }
}
