// Auto-generated by AE2Unity.
// Metadata-only preview. Re-export with Bake animation enabled for full composition playback.
// Source comp: Mass2_Mass_Revision (1080x1080, 24 fps, 5s)
//
// Exported layers:
// - 1: Shape Layer 1 [shape], blend=5212, opacity=100
// - 2: RIght [precomp], blend=5212, opacity=100
// - 3: Left [precomp], blend=5212, opacity=100
// - 4: Down [precomp], blend=5212, opacity=100
// - 5: Up [precomp], blend=5212, opacity=100
// - 6: Back [precomp], blend=5212, opacity=100
//
// Import warnings:
// - Shape Layer 1: 3D layers are not shader-converted in the MVP and should be baked.
// - Shape Layer 1: blend mode '5212' is not implemented yet.
// - RIght: 3D layers are not shader-converted in the MVP and should be baked.
// - RIght: blend mode '5212' is not implemented yet.
// - Left: 3D layers are not shader-converted in the MVP and should be baked.
// - Left: blend mode '5212' is not implemented yet.
// - Down: 3D layers are not shader-converted in the MVP and should be baked.
// - Down: blend mode '5212' is not implemented yet.
// - Up: 3D layers are not shader-converted in the MVP and should be baked.
// - Up: blend mode '5212' is not implemented yet.
// - Back: 3D layers are not shader-converted in the MVP and should be baked.
// - Back: blend mode '5212' is not implemented yet.
Shader "AE2Unity/Generated/Mass2_Mass_Revision"
{
    Properties
    {
        _MainTex ("Texture", 2D) = "white" {}
        [NoScaleOffset] _FrameAtlas0 ("Baked Frames 0", 2D) = "black" {}
        [NoScaleOffset] _FrameAtlas1 ("Baked Frames 1", 2D) = "black" {}
        [NoScaleOffset] _FrameAtlas2 ("Baked Frames 2", 2D) = "black" {}
        [NoScaleOffset] _FrameAtlas3 ("Baked Frames 3", 2D) = "black" {}
        _Tint ("Tint", Color) = (1, 1, 1, 1)
        _Opacity ("Opacity", Range(0, 1)) = 1
        _AeTime ("AE Time", Float) = 0
        [Toggle] _AutoPlay ("Auto Play", Float) = 0
        [Toggle] _Loop ("Loop", Float) = 1
        _PlaybackSpeed ("Playback Speed", Float) = 1
        [HideInInspector] _BakedFrameCount ("Baked Frame Count", Float) = 0
        [HideInInspector] _FramesPerAtlas ("Frames Per Atlas", Float) = 1
        [HideInInspector] _AtlasColumns ("Atlas Columns", Float) = 1
        [HideInInspector] _AtlasRows ("Atlas Rows", Float) = 1
        [HideInInspector] _FrameRate ("Frame Rate", Float) = 24
        [HideInInspector] _Duration ("Duration", Float) = 1
        _CompSize ("Comp Size", Vector) = (1080, 1080, 0.00092593, 0.00092593)
    }
    SubShader
    {
        Tags { "RenderPipeline"="UniversalPipeline" "Queue"="Transparent" "RenderType"="Transparent" "IgnoreProjector"="True" }
        Blend SrcAlpha OneMinusSrcAlpha
        Cull Off
        ZWrite Off
        Pass
        {
            Name "AE2UnityGeneratedPreview"
            HLSLPROGRAM
            #pragma vertex Vert
            #pragma fragment Frag
            #pragma target 3.0
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            struct Attributes { float4 positionOS : POSITION; float2 uv : TEXCOORD0; half4 color : COLOR; };
            struct Varyings { float4 positionHCS : SV_POSITION; float2 uv : TEXCOORD0; half4 color : COLOR; };
            TEXTURE2D(_MainTex);
            SAMPLER(sampler_MainTex);
            TEXTURE2D(_FrameAtlas0);
            SAMPLER(sampler_FrameAtlas0);
            TEXTURE2D(_FrameAtlas1);
            SAMPLER(sampler_FrameAtlas1);
            TEXTURE2D(_FrameAtlas2);
            SAMPLER(sampler_FrameAtlas2);
            TEXTURE2D(_FrameAtlas3);
            SAMPLER(sampler_FrameAtlas3);
            CBUFFER_START(UnityPerMaterial)
                float4 _MainTex_ST;
                half4 _Tint;
                half _Opacity;
                float _AeTime;
                float _AutoPlay;
                float _Loop;
                float _PlaybackSpeed;
                float _BakedFrameCount;
                float _FramesPerAtlas;
                float _AtlasColumns;
                float _AtlasRows;
                float _FrameRate;
                float _Duration;
                float4 _CompSize;
            CBUFFER_END
            Varyings Vert(Attributes input)
            {
                Varyings output;
                output.positionHCS = TransformObjectToHClip(input.positionOS.xyz);
                output.uv = TRANSFORM_TEX(input.uv, _MainTex);
                output.color = input.color;
                return output;
            }
            half4 SampleBakedFrame(float2 uv)
            {
                float frameRate = max(1.0, _FrameRate);
                float duration = max(1.0 / frameRate, _Duration);
                float playbackTime = _AutoPlay > 0.5 ? _Time.y * _PlaybackSpeed : _AeTime;
                playbackTime = max(0.0, playbackTime);
                playbackTime = _Loop > 0.5 ? fmod(playbackTime, duration) : min(playbackTime, duration - 0.5 / frameRate);
                float frameIndex = min(_BakedFrameCount - 1.0, floor(playbackTime * frameRate + 0.0001));
                float framesPerAtlas = max(1.0, _FramesPerAtlas);
                float atlasIndex = floor(frameIndex / framesPerAtlas);
                float localIndex = frameIndex - atlasIndex * framesPerAtlas;
                float columns = max(1.0, _AtlasColumns);
                float rows = max(1.0, _AtlasRows);
                float column = fmod(localIndex, columns);
                float row = floor(localIndex / columns);
                float2 atlasUv = (float2(column, row) + uv) / float2(columns, rows);
                if (atlasIndex < 0.5) return SAMPLE_TEXTURE2D(_FrameAtlas0, sampler_FrameAtlas0, atlasUv);
                if (atlasIndex < 1.5) return SAMPLE_TEXTURE2D(_FrameAtlas1, sampler_FrameAtlas1, atlasUv);
                if (atlasIndex < 2.5) return SAMPLE_TEXTURE2D(_FrameAtlas2, sampler_FrameAtlas2, atlasUv);
                return SAMPLE_TEXTURE2D(_FrameAtlas3, sampler_FrameAtlas3, atlasUv);
            }
            half4 Frag(Varyings input) : SV_Target
            {
                half4 color = _BakedFrameCount > 0.5
                    ? SampleBakedFrame(input.uv)
                    : SAMPLE_TEXTURE2D(_MainTex, sampler_MainTex, input.uv);
                color *= _Tint * input.color;
                color.a *= _Opacity;
                return color;
            }
            ENDHLSL
        }
    }
    FallBack Off
}
